name: 'test'

on:
  push

jobs:
  deploy:
    name: extract ssm trust-me
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::668096754719:role/t_rodman
        aws-region: us-west-2  

    - uses: dkershner6/aws-ssm-getparameters-action@v1
      with:
          parameterPairs: "/trust-me = test"
          # The part before equals is the ssm parameterName, and after is the ENV Variable name for the workflow.
          # No limit on number of parameters. You can put new lines and spaces in as desired, they get trimmed out.
          withDecryption: "true" # defaults to true
