name: 'test'

on:
  push

env:
  ACTIONS_RUNNER_DEBUG: True
  ACTIONS_STEP_DEBUG: true
jobs:
  deploy:
    name: extract ssm trust-me
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::668096754719:role/t_rodman
        aws-region: us-west-2  

    - uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/trust-me"
        env_variable_name: "test"
        
    - name: "Build & Deploy"
      run: |
        echo "flag: $TEST" | sed 's/./& /g'
